grails-app/domain/example/ScheduledEvent.groovy
package example

class ScheduledEvent {
    Long id
    String title
    boolean active
    EventType eventType
    int numberOfSpeakers
    double admissionPrice
    String description
    Date eventDate
    Date lastUpdated
    Date dateCreated

    static constraints = {
        title blank: false, nullable: false, unique: false
        description blank: false, nullable: false, unique: false
        eventDate nullable: false, unique: false
        lastUpdated()
        dateCreated()
    }

    static mapping = {
        description type: 'text'
    }

    @Override
    String toString() {
        return title
    }
}

grails-app/controllers/example/ScheduledEventController.groovy
package example

import au.com.bytecode.opencsv.CSVWriter
import grails.transaction.Transactional

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class ScheduledEventController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def grailsApplication  //inject GrailsApplication

    def downloadReport() {
        response.setHeader("Content-disposition", "attachment; filename=events.csv")
        response.contentType = "text/csv"
        def out = response.outputStream
        out.withWriter { writer ->

            String[] properties = new String[9]
            def csvWriter = new CSVWriter(writer)

            // create the headings
            properties[0] = "Title"
            properties[1] = "Description"
            properties[2] = "Active"
            properties[3] = "Number of Speakers"
            properties[4] = "Admission Price"
            properties[5] = "Event Date"
            properties[6] = "Updated"
            properties[7] = "Created"
            properties[8] = "Event Type"
            csvWriter.writeNext(properties)
            // fill in data
            ScheduledEvent.findAll().each { scheduledEvent ->
                properties[0] = scheduledEvent.title
                properties[1] = scheduledEvent.description
                properties[2] = scheduledEvent.active
                properties[3] = scheduledEvent.numberOfSpeakers
                properties[4] = scheduledEvent.admissionPrice
                properties[5] = scheduledEvent.eventDate
                properties[6] = scheduledEvent.lastUpdated
                properties[7] = scheduledEvent.dateCreated
                properties[8] = scheduledEvent.eventType
                csvWriter.writeNext(properties)
            }
            csvWriter.flush()
        }
    }


    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond ScheduledEvent.list(params), model: [scheduledEventInstanceCount: ScheduledEvent.count()]
    }

    def show(ScheduledEvent scheduledEventInstance) {
        respond scheduledEventInstance
    }

    def create() {
        respond new ScheduledEvent(params)
    }

    @Transactional
    def save(ScheduledEvent scheduledEventInstance) {
        if (scheduledEventInstance == null) {
            notFound()
            return
        }

        if (scheduledEventInstance.hasErrors()) {
            respond scheduledEventInstance.errors, view: 'create'
            return
        }

        scheduledEventInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'domain.scheduledEvent', default: 'ScheduledEvent'), scheduledEventInstance.id])
                redirect scheduledEventInstance
            }
            '*' { respond scheduledEventInstance, [status: CREATED] }
        }
    }

    def edit(ScheduledEvent scheduledEventInstance) {
        respond scheduledEventInstance
    }

    @Transactional
    def update(ScheduledEvent scheduledEventInstance) {
        if (scheduledEventInstance == null) {
            notFound()
            return
        }

        if (scheduledEventInstance.hasErrors()) {
            respond scheduledEventInstance.errors, view: 'edit'
            return
        }

        scheduledEventInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'domain.scheduledEvent', default: 'ScheduledEvent'), scheduledEventInstance.id])
                redirect scheduledEventInstance
            }
            '*' { respond scheduledEventInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(ScheduledEvent scheduledEventInstance) {

        if (scheduledEventInstance == null) {
            notFound()
            return
        }

        scheduledEventInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'domain.scheduledEvent', default: 'ScheduledEvent'), scheduledEventInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'domain.scheduledEvent', default: 'ScheduledEvent'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/scheduledEvent/_form.gsp
<%@ page import="example.ScheduledEvent" %>
<%@ page import="example.EventType" %>
<hr>

<div class="form-group">
    <label for="title" class="col-xs-3 control-label">
        <span class="glyphicon glyphicon-asterisk"/></span><g:message code="scheduledEvent.label.title"/>
    </label>

    <div class="col-xs-9">
        <formHelper:getFocus name="title" class="form-control" value="${scheduledEventInstance?.title}" required=""
                             actionValue="${actionName}"/>
    </div>
</div>

<div class="form-group">
    <label for="title" class="col-xs-3 control-label ">
        <span class="glyphicon glyphicon-asterisk"/></span><g:message code="scheduledEvent.label.active"/>
    </label>

    <div class="col-xs-9 ">
        <g:checkBox name="active" class="form-control-checkbox" value="${scheduledEventInstance?.active}"/>
    </div>
</div>

<div class="form-group">
    <label for="eventType" class="col-xs-3 control-label">
        <span class="glyphicon glyphicon-asterisk"/></span><g:message code="scheduledEvent.label.eventType"/>
    </label>

    <div class="col-xs-9">
        <g:select class="form-control" id="eventType" name='eventType' value="${scheduledEventInstance?.eventType?.id}"
                  noSelection="${['null': 'Select One...']}"
                  from='${EventType?.findAll()}'
                  optionKey="id" optionValue="name" required="">
        </g:select>
    </div>
</div>

<div class="form-group">
    <label for="title" class="col-xs-3 control-label">
        <span class="glyphicon glyphicon-asterisk"/></span><g:message code="scheduledEvent.label.numberOfSpeakers"/>
    </label>

    <div class="col-xs-9">

        <g:field class="form-control" type="number" min="1" max="1000000" step="0.0001" name="numberOfSpeakers"
                 value="${scheduledEventInstance?.numberOfSpeakers}" required=""/>
    </div>
</div>

<div class="form-group">
    <label for="title" class="col-xs-3 control-label">
        <span class="glyphicon glyphicon-asterisk"/></span><g:message code="scheduledEvent.label.admissionPrice"/>
    </label>

    <div class="col-xs-9">
        <g:field type="number" min="0" max="1000000" step="0.0001" name="admissionPrice" class="form-control"
                 value="${formatNumber(number: scheduledEventInstance.admissionPrice, g.message(code: 'default.number.format'))}"/>
    </div>
</div>

<div class="form-group">
    <label for="title" class="col-xs-3 control-label">
        <span class="glyphicon glyphicon-asterisk"/></span><g:message code="scheduledEvent.label.eventDate"
                                                                      default="Event Date"/>
    </label>

    <div class="col-xs-9">
        <g:textField class="form-control dateTimePicker" name="eventDate"
                     value="${formatDate(format: 'MM/dd/yyyy', date: scheduledEventInstance?.eventDate)}" required=""/>
    </div>

</div>

<div class="form-group">
    <label for="title" class="col-xs-3 control-label">
        <span class="glyphicon glyphicon-asterisk"/></span><g:message code="scheduledEvent.label.description"/>
    </label>

    <div class="col-xs-9">
        <textarea name="description" class="form-control" rows="5"
                  required="">${scheduledEventInstance?.description}</textarea>
    </div>
    <hr>
</div>

grails-app/views/scheduledEvent/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'domain.scheduledEvent', default: 'Scheduled Event')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div class="container">
    <div class="row grailsDomainNav">
        <div class="col-xs-12">
            <ul>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
            </ul>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12">
            <h1><g:message code="default.create.label" args="[entityName]"/></h1>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisi sapien, pellentesque sit amet tempus in, ultrices at tellus. Curabitur ut lacus a libero accumsan aliquet. Phasellus molestie rutrum diam, in pulvinar arcu blandit in.</p>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${scheduledEventInstance}">
                <ul class="errors" role="alert">
                    <g:eachError bean="${scheduledEventInstance}" var="error">
                        <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                                error="${error}"/></li>
                    </g:eachError>
                </ul>
            </g:hasErrors>
        </div>
    </div>


    <sec:ifAnyGranted roles="ROLE_ADMIN">

        <g:form class="form-horizontal formNoTopPadOrMargin" url="[resource: scheduledEventInstance, action: 'save']">
            <fieldset class="form">
                <g:render template="form"/>
            </fieldset>
            <fieldset class="buttons">
                <button name="create" class="btn btn-success buttonWithForm" name="create">
                    <span class="fa fa-save fa-lg" aria-hidden="true">Create</span>
                </button>
            </fieldset>
        </g:form>

    </sec:ifAnyGranted>

</body>
</html>

grails-app/views/scheduledEvent/edit.gsp
<%@ page import="example.ScheduledEvent" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'domain.scheduledEvent', default: 'Scheduled Event')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div class="container">
    <div class="row grailsDomainNav">
        <div class="col-xs-12">
            <ul>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
                <sec:ifAnyGranted roles="ROLE_ADMIN">
                    <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                                          args="[entityName]"/></g:link></li>
                </sec:ifAnyGranted>
            </ul>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12">
            <h1><g:message code="default.edit.label" args="[entityName]"/></h1>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisi sapien, pellentesque sit amet tempus in, ultrices at tellus. Curabitur ut lacus a libero accumsan aliquet. Phasellus molestie rutrum diam, in pulvinar arcu blandit in.</p>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${scheduledEventInstance}">
                <ul class="errors" role="alert">
                    <g:eachError bean="${scheduledEventInstance}" var="error">
                        <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                                error="${error}"/></li>
                    </g:eachError>
                </ul>
            </g:hasErrors>
        </div>
    </div>



    <g:form class="form-horizontal formNoTopPadOrMargin" url="[resource: scheduledEventInstance, action: 'update']" method="PUT">
        <g:hiddenField name="version" value="${scheduledEventInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <button name="update" class="btn btn-success buttonWithForm" action="update">
                <span class="fa fa-save fa-lg" aria-hidden="true">Update</span>
            </button>
        </fieldset>
    </g:form>
</div>

</body>
</html>

grails-app/views/scheduledEvent/index.gsp
<%@ page import="example.ScheduledEvent" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'domain.scheduledEvent', default: 'Scheduled Event')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div class="container">
    <div class="row grailsDomainNav">
        <div class="col-xs-12">
            <ul>
                <sec:ifAnyGranted roles="ROLE_ADMIN">
                    <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]"/></g:link></li>
                </sec:ifAnyGranted>
            </ul>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12">
            <h1><g:message code="default.list.label" args="[entityName]"/></h1>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisi sapien, pellentesque sit amet tempus in, ultrices at tellus. Curabitur ut lacus a libero accumsan aliquet. Phasellus molestie rutrum diam, in pulvinar arcu blandit in.</p>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
        </div>
    </div>


    <table class="table table-bordered table-striped dataTable" id="defaultDataTable">
        <thead>
        <tr>
            <th class="sortableHeader"><g:message code="generic.th.title"/></th>
            <th class="sortableHeader"><g:message code="generic.th.description"/></th>
            <th class="sortableHeader"><g:message code="generic.th.date"/></th>
        </tr>
        </thead>
        <tbody>
        <g:each in="${scheduledEventInstanceList}" status="i" var="scheduledEventInstance">
            <tr class="hover"
                onclick='document.location = "<g:createLink action='show' id="${scheduledEventInstance.id}"/>" '>
                <td>${fieldValue(bean: scheduledEventInstance, field: "title")}</td>
                <td>${fieldValue(bean: scheduledEventInstance, field: "description")}</td>
                <td class="text-nowrap"><g:formatDate format="MM/dd/yyyy"
                                                      date="${scheduledEventInstance.eventDate}"/></td>
            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="row">
        <g:form controller="scheduledEvent" action="downloadReport">
            <button name="download" type="submit" class=" btn btn-success btn-block buttonWithForm"
                    aria-label="Left Align" action="downloadReport">
                <span class="fa fa-download fa-lg" aria-hidden="true">Export</span>
            </button>
        </g:form>
    </div>
</div>

</body>
</html>

grails-app/views/scheduledEvent/show.gsp
<%@ page import="example.ScheduledEvent" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'domain.scheduledEvent', default: 'Scheduled Event')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div class="container">
    <div class="row grailsDomainNav">
        <div class="col-xs-12">
            <ul>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
                <sec:ifAnyGranted roles="ROLE_ADMIN">
                    <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                                          args="[entityName]"/></g:link></li>
                </sec:ifAnyGranted>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <h1><g:message code="default.list.label" args="[entityName]"/></h1>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisi sapien, pellentesque sit amet tempus in, ultrices at tellus. Curabitur ut lacus a libero accumsan aliquet. Phasellus molestie rutrum diam, in pulvinar arcu blandit in.</p>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
        </div>
    </div>

    <hr>
    <span class="showDisplay">
        <g:if test="${scheduledEventInstance?.title}">
            <div class="row">
                <div class="col-xs-3 showLabel">
                    <g:message code="scheduledEvent.label.title"/>
                </div>

                <div class="col-xs-9 displayValue">
                    ${scheduledEventInstance.title}
                </div>
            </div>
        </g:if>

        <g:if test="${scheduledEventInstance?.active}">
            <div class="row">
                <div class="col-xs-3 showLabel">
                    <g:message code="scheduledEvent.label.active"/>
                </div>

                <div class="col-xs-9 displayValue">
                    ${scheduledEventInstance.active}
                </div>
            </div>
        </g:if>

        <g:if test="${scheduledEventInstance?.eventType}">
            <div class="row">
                <div class="col-xs-3 showLabel">
                    <g:message code="scheduledEvent.label.eventType"/>
                </div>

                <div class="col-xs-9 displayValue">
                    ${scheduledEventInstance.eventType}
                </div>
            </div>
        </g:if>

        <g:if test="${scheduledEventInstance?.numberOfSpeakers}">
            <div class="row">
                <div class="col-xs-3 showLabel">
                    <g:message code="scheduledEvent.label.numberOfSpeakers"/>
                </div>

                <div class="col-xs-9 displayValue">
                    ${scheduledEventInstance.numberOfSpeakers}
                </div>
            </div>
        </g:if>

        <g:if test="${scheduledEventInstance?.admissionPrice}">
            <div class="row">
                <div class="col-xs-3 showLabel">
                    <g:message code="scheduledEvent.label.admissionPrice"/>
                </div>

                <div class="col-xs-9 displayValue">
                    <g:formatNumber number="${scheduledEventInstance.admissionPrice}" type="currency" currencyCode="USD"/>
                </div>
            </div>
        </g:if>

        <g:if test="${scheduledEventInstance?.description}">
            <div class="row">
                <div class="col-xs-3 showLabel">
                    <g:message code="scheduledEvent.label.description"/>
                </div>

                <div class="col-xs-9 displayValue">
                    ${scheduledEventInstance.description}
                </div>
            </div>
        </g:if>

        <g:if test="${scheduledEventInstance?.eventDate}">
            <div class="row">
                <div class="col-xs-3 showLabel">
                    <g:message code="scheduledEvent.label.eventDate"/>
                </div>

                <div class="col-xs-9 displayValue">
                    <g:formatDate format="yyyy-MM-dd" date="${scheduledEventInstance.eventDate}"/>
                </div>
            </div>
        </g:if>

        <g:if test="${scheduledEventInstance?.lastUpdated}">
            <div class="row">
                <div class="col-xs-3 showLabel">
                    <g:message code="generic.label.lastUpdated"/>
                </div>

                <div class="col-xs-9 displayValue">
                    ${scheduledEventInstance.lastUpdated}
                </div>
            </div>
        </g:if>

        <g:if test="${scheduledEventInstance?.dateCreated}">
            <div class="row">
                <div class="col-xs-3 showLabel">
                    <g:message code="generic.label.dateCreated"/>
                </div>

                <div class="col-xs-9 displayValue">
                    ${scheduledEventInstance.dateCreated}
                </div>
            </div>
        </g:if>
        <hr>
    </span>
    <sec:ifAnyGranted roles="ROLE_ADMIN">
        <div class="row containerButtons">
            <fieldset class="buttons">
                <g:form id="${scheduledEventInstance?.id}" controller="scheduledEvent" action="edit" method="post">
                    <g:hiddenField name="version" value="${scheduledEventInstance?.version}"/>
                    <button name="edit" class="btn btn-success btn-block buttonWithForm"
                            resource="${scheduledEventInstance}"
                            action="edit">
                        <span class="fa fa-edit fa-lg" aria-hidden="true">Edit</span>
                    </button>
                </g:form>
                <g:form id="${scheduledEventInstance?.id}" controller="scheduledEvent" method="delete" action="delete">
                    <button name="delete" class=" btn btn-danger btn-block buttonWithForm" aria-label="Left Align"
                            resource="${scheduledEventInstance}" action="delete"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">

                        <span class="fa fa-remove fa-lg " aria-hidden="true">Delete</span>
                    </button>
                </g:form>
            </fieldset>
        </div>
    </sec:ifAnyGranted>
</div>
</body>
</html>